import type { NewsPayload } from "./NewsPayload.js"
import type { TickerPayload } from "./TickerPayload.js"
import type { UtilityPayload } from "./UtilityPayload.js"

export type SlotKind = "news" | "ticker" | "utility" | "sponsored" | "portfolio"
export type SlotLayout = "single" | "grid"

// SlotKind includes "sponsored" and "portfolio" as reserved future kinds.
// Their payload types do not exist yet, so a discriminant check on those
// values will narrow SlotPayload to `never`. Add the payload types when
// these kinds become live. "utility" (CH 03) is locally generated by the
// daemon — never returned by /me/content/next.
export type SlotPayload = NewsPayload | TickerPayload | UtilityPayload
